# Generated by Django 4.1.6 on 2023-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_mypodcast', models.CharField(max_length=202)),
                ('about_description', models.TextField()),
                ('about_me_image', models.ImageField(upload_to='')),
                ('about_me_description', models.TextField()),
            ],
        ),
    ]
