# Generated by Django 4.1.6 on 2023-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_rename_comment_commentarticle_commentblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentarticle',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='Name',
            field=models.CharField(default=1, max_length=202),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='Phone',
            field=models.CharField(default=1, max_length=202),
            preserve_default=False,
        ),
    ]
