# Generated by Django 4.1.6 on 2023-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_description_commentarticle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='Name',
            field=models.CharField(blank=True, max_length=202, null=True),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='Phone',
            field=models.CharField(blank=True, max_length=202, null=True),
        ),
    ]
