# Generated by Django 4.1.6 on 2023-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_commentarticle_email_alter_commentarticle_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentblog',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='Name',
            field=models.CharField(blank=True, max_length=202, null=True),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='Phone',
            field=models.CharField(blank=True, max_length=202, null=True),
        ),
    ]
