# Generated by Django 4.1.6 on 2023-02-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_description_commentblog_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='blog.category'),
            preserve_default=False,
        ),
    ]
