# Generated by Django 4.1.6 on 2023-02-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_season_article_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='blog.season'),
        ),
    ]
