# Generated by Django 4.1.6 on 2023-02-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='episode',
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article'),
            preserve_default=False,
        ),
    ]
